# Generated by Django 4.0.5 on 2022-06-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentgroup_students_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, choices=[('Petrenko', 'Петренко'), ('Ivanenko', 'Иваненоко'), ('Sidorov', 'Сидоров'), ('Maximenko', 'Максименко'), ('Mykhailenko', 'Михайленко')], max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
